project_id = "mobikymhzchzakwzpqep"

[functions.reset-daily-counters]
verify_jwt = false

[functions.complete-task]
verify_jwt = true

[functions.deposit]
verify_jwt = true

[functions.withdraw]
verify_jwt = true

[functions.upgrade-plan]
verify_jwt = true